name: Runreport browser launch

on:
  push: 
    branches: ["main"]
  workflow_dispatch:
  
jobs:
    genreport:
      runs-on: ubuntu-latest
      steps:
        - name: test command
          run: 'pwd'

        - name: setup javasdk
          uses: actions/setup-java@v1
          with:
            java-version: '17'

        - name: checkout code
          uses: actions/checkout@v3
          with:
            ref: main
            sparse-checkout: 'CucumberTestNGTestAutomation'
            sparse-checkout-cone-mode: false
            
        - name: ls command
          run: 'ls /home/runner/work/GenReport/GenReport/CucumberTestNGTestAutomation'
          
        - name: pwd command
          run: 'pwd'

        - name: compile java
          run: |
            pushd './CucumberTestNGTestAutomation'
            mvn clean compile
            mvn test
        - name: run cucumber test
          run: |
            java -cp runners.CucumberRunnerTest
            
    
