name: Run Tests and Email Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Run Tests
        run: |
          cd CucumberTestNGTestAutomation
          mvn test

      - name: Send Email with Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: monisha131211@gmail.com
          password: kmschasntnlnlfop
          subject: Test Report - ${{ github.repository }}
          to: mageshgovindarajaulu@gmail.com
          from: monisha131211@gmail.com
          secure: true
          body: |
            Hello,

            Please find the test report attached.
            
            Regards,
            GitHub Actions
          attachments: CucumberTestNGTestAutomation/test-output/emailable-report.html
